/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class sistema extends javax.swing.JFrame {
   
  conexion cc = new conexion();
  Connection con =  cc.conexion();
  /**
   * Creates new form sistema
   */
  public sistema() {
    initComponents();
    this.setLocationRelativeTo(null);
    this.getContentPane().setBackground(getBackground());
    mostrarDatos();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    btnNuevo = new javax.swing.JButton();
    txtReferencia = new javax.swing.JTextField();
    txtPrecio = new javax.swing.JTextField();
    txtPeso = new javax.swing.JTextField();
    txtStock = new javax.swing.JTextField();
    cbCategoria = new javax.swing.JComboBox<>();
    btnGuardar = new javax.swing.JButton();
    btnEditar = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    dateFechaCreacion = new com.toedter.calendar.JDateChooser();
    jLabel8 = new javax.swing.JLabel();
    btnInicio = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaProductos = new javax.swing.JTable();
    jLabel9 = new javax.swing.JLabel();
    txtBuscar = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    jPanel1.setBackground(new java.awt.Color(153, 153, 0));
    jPanel1.setForeground(new java.awt.Color(51, 51, 51));

    jLabel1.setText("Nombre");

    jLabel2.setText("Referencia");

    jLabel3.setText("Precio");

    jLabel4.setText("Peso");

    jLabel5.setText("Categoria");

    jLabel6.setText("Stock");

    jLabel7.setText("Fecha Creacion");

    btnNuevo.setText("Nuevo");
    btnNuevo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNuevoActionPerformed(evt);
      }
    });

    txtPeso.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtPesoActionPerformed(evt);
      }
    });

    txtStock.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtStockActionPerformed(evt);
      }
    });

    cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida Fria", "Bebida Caliente", "Jugos", "Postres" }));
    cbCategoria.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbCategoriaActionPerformed(evt);
      }
    });

    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });

    btnEditar.setText("Actualizar");
    btnEditar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarActionPerformed(evt);
      }
    });

    btnEliminar.setText("Eliminar");
    btnEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
    jLabel8.setText("PRODUCTOS");

    btnInicio.setText("Inicio");
    btnInicio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnInicioActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(65, 65, 65)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2)
              .addComponent(jLabel3)
              .addComponent(jLabel4)
              .addComponent(jLabel5))
            .addGap(52, 52, 52)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtPeso)
              .addComponent(txtPrecio)
              .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(txtReferencia)
              .addComponent(txtNombre)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel6)
              .addComponent(jLabel7))
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtStock)
              .addComponent(dateFechaCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addGap(70, 70, 70))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(btnNuevo)
        .addGap(18, 18, 18)
        .addComponent(btnGuardar)
        .addGap(15, 15, 15)
        .addComponent(btnEditar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnEliminar)
        .addGap(0, 17, Short.MAX_VALUE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(132, 132, 132)
            .addComponent(jLabel8))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(138, 138, 138)
            .addComponent(btnInicio)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addComponent(jLabel8)
        .addGap(28, 28, 28)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5)
          .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel7)
          .addComponent(dateFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(30, 30, 30)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnNuevo)
          .addComponent(btnGuardar)
          .addComponent(btnEditar)
          .addComponent(btnEliminar))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnInicio)
        .addContainerGap())
    );

    tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {},
        {},
        {},
        {}
      },
      new String [] {

      }
    ));
    tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaProductosMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tablaProductos);

    jLabel9.setText("Busqueda:");

    txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtBuscarKeyReleased(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(8, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(15, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel9)
          .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtPesoActionPerformed

  private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtStockActionPerformed
public void mostrarDatos(){
  String[] titulos={"ID", "Nombre Producto", "Referencia","Precio","Peso","Categoria","stock","fecha Creacion"};
  String[] registros = new String[8];
  DefaultTableModel modelo = new DefaultTableModel(null,titulos);
  String SQL = "select * from productos";
  try {
    
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery(SQL);
    
    while(rs.next()){
      registros[0]=rs.getString("id_producto");
      registros[1]=rs.getString("nombre_producto");
      registros[2]=rs.getString("referencia");
      registros[3]=rs.getString("precio");
      registros[4]=rs.getString("peso");
      registros[5]=rs.getString("categoria");
      registros[6]=rs.getString("stock");
      registros[7]=rs.getString("fecha_creacion");
      
      modelo.addRow(registros);
      
    }
    
    tablaProductos.setModel(modelo);
    
  } catch (Exception e) {
    JOptionPane.showMessageDialog(null,"Error al mostrar datos"+ e.getMessage());
  }
}

public void filtrarDatos(String valor){
  String[] titulos={"ID", "Nombre Producto", "Referencia","Precio","Peso","Categoria","stock","fecha Creacion"};
  String[] registros = new String[8];
  DefaultTableModel modelo = new DefaultTableModel(null,titulos);
  
  String SQL = "select * from productos where nombre_producto like '%"+ valor +"%'";
  try {
    
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery(SQL);
    
    while(rs.next()){
      registros[0]=rs.getString("id_producto");
      registros[1]=rs.getString("nombre_producto");
      registros[2]=rs.getString("referencia");
      registros[3]=rs.getString("precio");
      registros[4]=rs.getString("peso");
      registros[5]=rs.getString("categoria");
      registros[6]=rs.getString("stock");
      registros[7]=rs.getString("fecha_creacion");
      
      modelo.addRow(registros);
      
    }
    
    tablaProductos.setModel(modelo);
    
  } catch (Exception e) {
    JOptionPane.showMessageDialog(null,"Error al mostrar datos"+ e.getMessage());
  }
}


  
  private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    limpiarDatos();
  }//GEN-LAST:event_btnNuevoActionPerformed

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    insertarDatos();
    limpiarDatos();
    mostrarDatos();
  }//GEN-LAST:event_btnGuardarActionPerformed

  private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
    
    int filaSeleccionada=tablaProductos.rowAtPoint(evt.getPoint());
    txtNombre.setText(tablaProductos.getValueAt(filaSeleccionada, 1).toString());
    txtReferencia.setText(tablaProductos.getValueAt(filaSeleccionada, 2).toString());
    txtPrecio.setText(tablaProductos.getValueAt(filaSeleccionada, 3).toString());
    txtPeso.setText(tablaProductos.getValueAt(filaSeleccionada, 4).toString());
    cbCategoria.setSelectedItem(tablaProductos.getValueAt(filaSeleccionada, 5));
    txtStock.setText(tablaProductos.getValueAt(filaSeleccionada, 6).toString());
    //dateFechaCreacion.setDate(tablaProductos.getValueAt(filaSeleccionada, 7));
   
    //dateFechaCreacion.setDate((Date)tablaProductos.getValueAt(filaSeleccionada, 7));
  }//GEN-LAST:event_tablaProductosMouseClicked

  private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    editarDatos();
    limpiarDatos();
    mostrarDatos();
  }//GEN-LAST:event_btnEditarActionPerformed

  private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    eliminarDatos();
    mostrarDatos();
    limpiarDatos();
  }//GEN-LAST:event_btnEliminarActionPerformed

  private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cbCategoriaActionPerformed

  private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
    filtrarDatos(txtBuscar.getText());    // TODO add your handling code here:
  }//GEN-LAST:event_txtBuscarKeyReleased

  private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
    inicio abrir=new inicio();
    abrir.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_btnInicioActionPerformed
  
  
  
  public void limpiarDatos(){
    txtNombre.setText("");
    txtReferencia.setText("");
    txtPrecio.setText("");
    txtPeso.setText("");
    txtStock.setText("");
    cbCategoria.setSelectedItem(null);
}
  
  public void insertarDatos(){
   try {
     String SQL="insert into productos(nombre_producto,referencia,precio,peso,categoria,stock,fecha_creacion) values (?,?,?,?,?,?,?)";
     PreparedStatement pst = con.prepareStatement(SQL);
     pst.setString(1, txtNombre.getText());
     pst.setString(2, txtReferencia.getText());
     pst.setInt(3, Integer.parseInt(txtPrecio.getText()));
     pst.setInt(4, Integer.parseInt(txtPeso.getText()));
     
     int seleccionado = cbCategoria.getSelectedIndex();
     pst.setString(5, cbCategoria.getItemAt(seleccionado));
     pst.setInt(6, Integer.parseInt(txtStock.getText()));
     SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
     String date = sdf.format(dateFechaCreacion.getDate());
     pst.setString(7,date);
          
     pst.execute();
     JOptionPane.showMessageDialog(null , "Registro Exitoso");      
     
   } catch (Exception e) {
     JOptionPane.showMessageDialog(null , "Error de Registro" + e.getMessage());
   }
 }

public void eliminarDatos(){
  
  int filaSeleccionada=tablaProductos.getSelectedRow();
  try {
    String SQL= "delete from productos where id_producto="+tablaProductos.getValueAt(filaSeleccionada, 0);
    Statement st=con.createStatement();
    int n=st.executeUpdate(SQL);
    if(n>0){
      JOptionPane.showMessageDialog(null, "Registro Eliminado");
    }
  } catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error al eliminar registro");
  }
}
  
  public void editarDatos(){
   try {
     String SQL="update productos set nombre_producto=?,referencia=?,precio=?,peso=?,categoria=?,stock=?,fecha_creacion=? where id_producto=?";
     
     int filaSeleccionada=tablaProductos.getSelectedRow();
     String dao=(String)tablaProductos.getValueAt(filaSeleccionada, 0);     
     
     PreparedStatement pst = con.prepareStatement(SQL);
     pst.setString(1, txtNombre.getText());
     pst.setString(2, txtReferencia.getText());
     pst.setInt(3, Integer.parseInt(txtPrecio.getText()));
     pst.setInt(4, Integer.parseInt(txtPeso.getText()));
     
     int seleccionado = cbCategoria.getSelectedIndex();
     pst.setString(5, cbCategoria.getItemAt(seleccionado));
     pst.setInt(6, Integer.parseInt(txtStock.getText()));
     SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
     String date = sdf.format(dateFechaCreacion.getDate());
     pst.setString(7,date);     
     pst.setString(8,dao);
     pst.execute();
     JOptionPane.showMessageDialog(null , "Registro editado exitosamente");    
     
   } catch (Exception e) {
     JOptionPane.showMessageDialog(null , "Error de edicion" + e.getMessage());
   }
  
  
  
  
  
}
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new sistema().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEditar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JButton btnInicio;
  private javax.swing.JButton btnNuevo;
  private javax.swing.JComboBox<String> cbCategoria;
  private com.toedter.calendar.JDateChooser dateFechaCreacion;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tablaProductos;
  private javax.swing.JTextField txtBuscar;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtPeso;
  private javax.swing.JTextField txtPrecio;
  private javax.swing.JTextField txtReferencia;
  private javax.swing.JTextField txtStock;
  // End of variables declaration//GEN-END:variables
}
